version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - run: |
          ci_webhook() {
            echo Sending webhook ...
            curl -X POST "https://fds-dev.now.sh/api/event-webhook" \
              -H "Content-Type: application/json" \
              -d"{`env | grep CIRCLE | sed 's/=/":"/' | sed 's/\(.*\)/"\1",/'` \"type\":\"$1\"}" #  pipeline.finished
          }

          ci_webhook pipeline.started

      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
            - v2-dependencies-

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: tests
          command: echo run tets

      - run:
          name: Build ...
          command: echo ok

      - deploy:
          name: Deploying ...
          command: echo deploying stuff

      - run:
          name: Running e2e tests ...
          command: echo e2e test run

      - run:
          when: always
          command: ci_webhook pipeline.finished
