version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo
    steps:
      - checkout
      - run: sleep 60s
      - run: echo "test 1 done"
  test-wait:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo
    steps:
      - checkout
      - run: sleep 60s
      - run: echo "test 2 done"
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - run: |
          # Cannot use scripts/ci_webhook.sh yet (before checkout)
          ci_webhook() {
            echo Sending webhook ...
            curl -X POST "https://fds-dev.herokuapp.com/api/event-webhook" \
              -H "Content-Type: application/json" \
              -d"{`env | grep CIRCLE | sed 's/=/":"/' | sed 's/\(.*\)/"\1",/'` \"type\":\"$1\"}"
          }

          ci_webhook pipeline.started

      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
            - v2-dependencies-

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: tests
          command: echo run tets

      - run:
          name: Build ...
          command: echo ok

      - deploy:
          name: Deploying ...
          command: echo deploying stuff

      - run:
          name: Running e2e tests ...
          command: echo e2e test run

      - run:
          when: on_success
          command: ./scripts/ci_webhook.sh pipeline.finished ", \"status\":\"success\""

      - run:
          when: on_fail
          command: ./scripts/ci_webhook.sh pipeline.finished ", \"status\":\"failure\""
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - test-wait:
          requires:
            - build
