version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10

  working_directory: ~/repo

jobs:
  track_start:
    <<: *defaults
    steps:
      - run: |
          # Cannot use scripts/ci_webhook.sh yet (before checkout)
          ci_webhook() {
            echo Sending webhook ...
            curl -X POST "https://fds-dev.now.sh/api/event-webhook" \
              -H "Content-Type: application/json" \
              -d"{`env | grep CIRCLE | sed 's/=/":"/' | sed 's/\(.*\)/"\1",/'` \"type\":\"$1\"}"
          }

          ci_webhook pipeline.started

  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
            - v2-dependencies-

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: tests
          command: echo run tets

      - run:
          name: Build ...
          command: echo ok

  deploy:
    <<: *defaults
    steps:
      - deploy:
          name: Deploying ...
          command: echo deploying stuff

      - run:
          name: Running e2e tests ...
          command: echo e2e test run

  track_end:
    <<: *defaults
    steps:
      - run:
          when: on_success
          command: ./scripts/ci_webhook.sh pipeline.finished ", \"status\":\"success\""

      - run:
          when: on_fail
          command: ./scripts/ci_webhook.sh pipeline.finished ", \"status\":\"failure\""

workflows:
  version: 2

  pipeline:
    jobs:
      - track_start
      - build:
          requires:
            - track_start
      - deploy_approval:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - deploy_approval
      - track_end:
          requires:
            - deploy
